spring.datasource.url=jdbc:mysql://localhost:3306/english_writing_support
spring.datasource.username=root
spring.datasource.password=nguyenhuytan2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true